### ISSUE TITLE
Xcode10 incompatibility with InjectionIII

### ISSUE THREAD

**Issue by polac24** [polac24/InjectionTDD#13]
When trying to use InjectionTDD with InjectionIII installed on Xcode10, simulator for XR such error logs to a console:

```
2018-10-28 22:34:35.378827+0100 InjectionTDD[72019:5332216] Error loading /Applications/InjectionIII.app/Contents/Resources/tvOSInjection.bundle/tvOSInjection:  dlopen(/Applications/InjectionIII.app/Contents/Resources/tvOSInjection.bundle/tvOSInjection, 265): no suitable image found.  Did find:
	/Applications/InjectionIII.app/Contents/Resources/tvOSInjection.bundle/tvOSInjection: mach-o, but not built for iOS simulator
2018-10-28 22:34:35.379020+0100 InjectionTDD[72019:5332216] Warning: Injection for Xcode not found. Please open Injection For Xcode.
```

**Comment by zenangst** [comment]
Hey @polac24, because we don't have ABI stability in Swift yet, we need to create two different bundles, one for Xcode 9 and one for Xcode 10. To use InjectionIII with Xcode 10 you should load the following bundle:

```
Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/iOSInjection10.bundle")?.load()
```

We have updated the README to include these instructions - https://github.com/johnno1962/InjectionIII

**Comment by polac24** [comment]
Sure, the fact that InjectionTDD loads tvOS bundle(note error message) when
trying to work on iphone’s simulator, is a bug.
I didn’t have time to investigate why during review it worked well but
after a merge I still get such error.

**Comment by zenangst** [comment]
@polac24 I can probably take a look at it and make a PR :) I think we need to revise the preprocessors. I'll keep you posted!

**Comment by zenangst** [comment]
@polac24 I made a PR for you :)
